### PR TITLE
Add settings for docker

### PR DESCRIPTION
**Pull request by murajun1978**
開発環境をDockerで構築
#### Setup
- Install [Docker](https://www.docker.com/products/docker)
- create .env.development

```
e.g. 

DATABASE_HOST=localhost
DATABASE_USERNAME=postgres
DATABASE_PASSWORD=
```

#### Build docker image
- bin/docker setup

#### Compose start
- bin/docker start

#### Database create
- bin/docker rake db:create

#### Database migrate 
- bin/docker rake db:migrate

#### Compose stop
- bin/docker stop

#### Rails console
- bin/docker rails c

#### RSpec
- bin/docker rspec

#### Rake
- bin/docker rake -T

#### TODO
- [x] `config/database.yml` のホストを `Docker` と `localhost` で共通設定にする
- [x] Dockerのスクリプトを追加 
- [x] Docker Setupスクリプトを追加

### CODE REVIEW

**Comment by murajun1978** [comment]
環境変数を使って、Dockerでもローカルでも動作するように修正した https://github.com/shinosakarb/tebukuro/pull/15/commits/e91df214bf1c5b7d07fd23b33a38d919ab7b14be

**Comment by murajun1978** [comment]
Databaseの `username` と `password` も環境変数を使うように修正 https://github.com/shinosakarb/tebukuro/pull/15/commits/1727d91f5a9045c5c13f4a44427a08d4ad4c367c

**Comment by murajun1978** [comment]
Dockerのスクリプトを追加 https://github.com/shinosakarb/tebukuro/pull/15/commits/aa67db11843f1fbfb3277ce742540b8a2dbae9ca

**Comment by chimame** [comment]
`docker-compose up`で立ち上げ後にlocalhost:3000叩くとdabaseが作られてないって怒られた。

**Comment by murajun1978** [comment]
だね、setupスクリプトを作る

**Comment by murajun1978** [comment]
```
  setup)
    docker-compose build
    docker-compose run --rm backend rails rake:db:setup
  ;;
```

**Comment by murajun1978** [comment]
setup スクリプトを追加したので確認してくださいな

**Comment by murajun1978** [comment]
なんだか安定しませんね、、

もう少し調査してみますー

**Comment by chimame** [comment]
`docker-compose up`→`tebukuro_backend_1 exited with code 1`
何かしないといけない？

**Comment by honeniq** [comment]
同じ状態ですー。

> Starting tebukuro_data_1
Starting tebukuro_db_1
Starting tebukuro_backend_1
Starting tebukuro_spring_1
Attaching to tebukuro_data_1, tebukuro_db_1, tebukuro_backend_1, tebukuro_spring_1
db_1       | LOG:  database system was shut down at 2016-10-31 15:00:04 UTC
db_1       | LOG:  MultiXact member wraparound protections are now enabled
db_1       | LOG:  autovacuum launcher started
db_1       | LOG:  database system is ready to accept connections
tebukuro_data_1 exited with code 0
spring_1   | [2016-10-31 15:02:15 +0000] [1] [server] started on /tmp/spring-0/20469551cd6998110fc73f1802c3de0e
backend_1  | => Booting Puma
backend_1  | => Rails 5.0.0.1 application starting in development on http://0.0.0.0:3000
backend_1  | => Run `rails server -h` for more startup options
backend_1  | A server is already running. Check /app/tmp/pids/server.pid.
backend_1  | Exiting
tebukuro_backend_1 exited with code 1

**Comment by murajun1978** [comment]
* bin/docker setup
* bin/docker rake db:create
* bin/docker rake db:migrate
* bin/docker start
* bin/docker stop

**Comment by murajun1978** [comment]
@honeniq たまーに、ちゃんと停止できてないのか原因は不明だけど `server.pid` が消えて無くて怒られる、、

**Comment by murajun1978** [comment]
スクリプトを別々にしてみた

手順 https://github.com/shinosakarb/tebukuro/pull/15#issuecomment-257322259

**Comment by chimame** [comment]
https://github.com/shinosakarb/tebukuro/pull/15#issuecomment-257322259 の手順でいけるんよね？

`bin/docker rake db:create`がエラーになるな。

> ERROR: No container found for spring_1

**Comment by honeniq** [comment]
先にspringのコンテナだけ実行しておけば``bin/docker rake db:create``できたけど、今度は``bin/docker start``するときにDBがコケるようになってしまた。

**Comment by murajun1978** [comment]
DBのコンテナが起動しっぱなしとかになってないかな？

ログが欲しい

**Comment by chimame** [comment]
bin/dockerの

```
docker-compose exec spring $@
```

を

```
docker-compose run spring spring $@
```

に変更したら`bin/docker rake db:create`は動いたけど、

>/app/vendor/bundle/ruby/2.3.0/gems/ffi-1.9.14/lib/ffi.rb:6:in `require': cannot load such file -- ffi_c (LoadError)
	from /app/vendor/bundle/ruby/2.3.0/gems/ffi-1.9.14/lib/ffi.rb:6:in `rescue in <top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/gems/ffi-1.9.14/lib/ffi.rb:3:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/gems/rb-inotify-0.9.7/lib/rb-inotify/native.rb:1:in `require'
	from /app/vendor/bundle/ruby/2.3.0/gems/rb-inotify-0.9.7/lib/rb-inotify/native.rb:1:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/gems/rb-inotify-0.9.7/lib/rb-inotify.rb:1:in `require'
	from /app/vendor/bundle/ruby/2.3.0/gems/rb-inotify-0.9.7/lib/rb-inotify.rb:1:in `<top (required)>'
	from /app/vendor/bundle/ruby/2.3.0/gems/listen-3.0.8/lib/listen/adapter/linux.rb:30:in `require'
	from /app/vendor/bundle/ruby/2.3.0/gems/listen-3.0.8/lib/listen/adapter/linux.rb:30:in `_configure'
	from /app/vendor/bundle/ruby/2.3.0/gems/listen-3.0.8/lib/listen/adapter/base.rb:45:in `block in configure'
	from /app/vendor/bundle/ruby/2.3.0/gems/listen-3.0.8/lib/listen/adapter/base.rb:40:in `each'
	from /app/vendor/bundle/ruby/2.3.0/gems/listen-3.0.8/lib/listen/adapter/base.rb:40:in `configure'
	from /app/vendor/bundle/ruby/2.3.0/gems/listen-3.0.8/lib/listen/adapter/base.rb:63:in `start'
	from /app/vendor/bundle/ruby/2.3.0/gems/listen-3.0.8/lib/listen/backend.rb:28:in `start'
	from /app/vendor/bundle/ruby/2.3.0/gems/listen-3.0.8/lib/listen/listener.rb:67:in `block in <class:Listener>'
	from /app/vendor/bundle/ruby/2.3.0/gems/listen-3.0.8/lib/listen/fsm.rb:120:in `instance_eval'
	from /app/vendor/bundle/ruby/2.3.0/gems/listen-3.0.8/lib/listen/fsm.rb:120:in `call'
	from /app/vendor/bundle/ruby/2.3.0/gems/listen-3.0.8/lib/listen/fsm.rb:91:in `transition_with_callbacks!'
	from /app/vendor/bundle/ruby/2.3.0/gems/listen-3.0.8/lib/listen/fsm.rb:57:in `transition'
	from /app/vendor/bundle/ruby/2.3.0/gems/listen-3.0.8/lib/listen/listener.rb:90:in `start'
	from /app/vendor/bundle/ruby/2.3.0/gems/spring-watcher-listen-2.0.1/lib/spring/watcher/listen.rb:27:in `start'
	from /usr/local/bundle/gems/spring-2.0.0/lib/spring/application.rb:70:in `start_watcher'
	from /usr/local/bundle/gems/spring-2.0.0/lib/spring/application.rb:79:in `preload'
	from /usr/local/bundle/gems/spring-2.0.0/lib/spring/application.rb:143:in `serve'
	from /usr/local/bundle/gems/spring-2.0.0/lib/spring/application.rb:131:in `block in run'
	from /usr/local/bundle/gems/spring-2.0.0/lib/spring/application.rb:125:in `loop'
	from /usr/local/bundle/gems/spring-2.0.0/lib/spring/application.rb:125:in `run'
	from /usr/local/bundle/gems/spring-2.0.0/lib/spring/application/boot.rb:19:in `<top (required)>'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /usr/local/lib/ruby/site_ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'

めっちゃ怒られた。
Docker詳しくないから的ハズレなことしてたらすまん。

**Comment by murajun1978** [comment]
Dockerのバージョンは？

**Comment by murajun1978** [comment]
わしのDocker 
Docker version 1.12.1, build 6f9534c

**Comment by chimame** [comment]
docker version
>Client:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.7.1
 Git commit:   6f9534c
 Built:        Thu Sep  8 10:31:18 2016
 OS/Arch:      darwin/amd64

>Server:
 Version:      1.12.1
 API version:  1.24
 Go version:   go1.6.3
 Git commit:   23cf638
 Built:        Thu Aug 18 17:52:38 2016
 OS/Arch:      linux/amd64

**Comment by murajun1978** [comment]
いっしょやな、、

bin/docker setupしてからでも同じ？

**Comment by chimame** [comment]
`bin/docker setup`をやってからやってるよ

`docker ps -a`
>CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS                      PORTS               NAMES
520397bff164        tebukuro_spring     "spring rake db:creat"   11 minutes ago      Exited (1) 11 minutes ago                       tebukuro_spring_run_1
dc02ff43d482        postgres:9.6        "/docker-entrypoint.s"   27 minutes ago      Exited (0) 5 seconds ago                        tebukuro_db_1
f33a06a33eb4        busybox             "sh"                     27 minutes ago      Exited (0) 11 minutes ago                       tebukuro_data_1

`docker images`

>docker images
REPOSITORY          TAG                 IMAGE ID            CREATED             SIZE
tebukuro_backend    latest              16732d977a83        15 minutes ago      1.101 GB
tebukuro_spring     latest              16732d977a83        15 minutes ago      1.101 GB
<none>              <none>              2ee878537080        34 minutes ago      1.1 GB
ruby                2.3.1               f865c7d10eb4        19 hours ago        729.5 MB
postgres            9.6                 0267f82ab721        38 hours ago        264.8 MB
busybox             latest              e02e811dd08f        3 weeks ago         1.093 MB


`bin/docker rake db:create`を叩いたら
>Starting tebukuro_data_1
Starting tebukuro_db_1
/app/vendor/bundle/ruby/2.3.0/gems/ffi-1.9.14/lib/ffi.rb:6:in `require': cannot load such file -- ffi_c (LoadError)

`docker ps`
>docker ps
CONTAINER ID        IMAGE               COMMAND                  CREATED             STATUS              PORTS               NAMES
dc02ff43d482        postgres:9.6        "/docker-entrypoint.s"   29 minutes ago      Up 38 seconds       5432/tcp            tebukuro_db_1

てな感じです。

**Comment by murajun1978** [comment]
postgresのコンテナだけ起動してるの

**Comment by murajun1978** [comment]
docker-compose execだとコンテナ起動してないとダメなのかな

あー、springサーバが起動してないからか、、

**Comment by murajun1978** [comment]
* bin/docker setup
* bin/docker start
* bin/docker rake db:create

ならよさげ

**Comment by chimame** [comment]
迷走してるｗ
ちなみに`bin/docker start`叩くと
>Starting tebukuro_data_1
Starting tebukuro_db_1
Creating tebukuro_backend_1
Creating tebukuro_spring_1
Attaching to tebukuro_data_1, tebukuro_db_1, tebukuro_spring_1, tebukuro_backend_1
db_1       | LOG:  database system was shut down at 2016-11-02 14:06:06 UTC
db_1       | LOG:  MultiXact member wraparound protections are now enabled
db_1       | LOG:  database system is ready to accept connections
db_1       | LOG:  autovacuum launcher started
tebukuro_data_1 exited with code 0
spring_1   | [2016-11-02 14:06:19 +0000] [1] [server] started on /tmp/spring-0/20469551cd6998110fc73f1802c3de0e
backend_1  | => Booting Puma
backend_1  | => Rails 5.0.0.1 application starting in development on http://0.0.0.0:3000
backend_1  | => Run `rails server -h` for more startup options
backend_1  | A server is already running. Check /app/tmp/pids/server.pid.
backend_1  | Exiting
tebukuro_backend_1 exited with code 1

**Comment by murajun1978** [comment]
それは app/tmp/pids/server.pid を削除してRetry!

**Comment by chimame** [comment]
dbがcreateされてないのにRailsあがるのか…
試してみます。

**Comment by honeniq** [comment]
>   data:
    image: busybox
    volumes:
      - "/var/lib/postgresql/data"

これ、マウントするのってこのパスじゃないと駄目ですか？

**Comment by murajun1978** [comment]
違ってもいいと思うよ

**Comment by chimame** [comment]
```
docker-compose up -d db && sleep 5
docker-compose run backend bin/rake db:setup
docker-compose up
```

上記のコマンドで立ち上がるのを確認しました。

**Comment by murajun1978** [comment]
ドキュメントをWikiに書くー

**Comment by murajun1978** [comment]
Thanks to everyone  :smile:

**Comment by springaki** [comment]
🎉

**Comment by chimame** [comment]
[LGTM](https://lgtm.in/i/MeFyEoBYp)

**Comment by murajun1978** [comment]
(・8・)

**Pull request merged**
