### PR TITLE
Add purchased attribute to Ticket model

### PR DESCRIPTION
**Pull request by gazayas**
### Overview:概要
Add `purchased` boolean attribute to the Ticket model

### Technical changes:技術的変更点
None

### Impact point:変更に関する影響箇所
None

### Change of UserInterface:UIの変更
None

I did not put any validations on this model. Does it need any?
Thank you.

### CODE REVIEW

**Comment by ytorii** [comment]
How do you recognize wheather the user has bought the ticket or not by this `purchased` flag? 
I guess `purchased: true` means all the users has bought the ticket, not each user.
Maybe TicketSubscriptions table added in #170 would help you because this table has user_id and ticket_id so you can recognize  which ticket the user has bought.

**Comment by murajun1978** [comment]
FYI: https://github.com/rails-api/active_model_serializers/blob/master/docs/general/serializers.md

**Comment by gazayas** [comment]
I see, so the flag should be in `TicketSubscriptions`
Thank you @murajun1978 for the reference.

`ticket.name` is not a foreign key. Do we need this attribute?
I thought a user would be associated with the event's tickets directly. Is this incorrect?

Sorry, I will close this issue and look at the issues more closely.

**Comment by murajun1978** [comment]
Yeah, it's correct.
but `purchased` attribute is not necessary for the ticket table.

We can get purchased tickets. 
like this
```
current_user.tickets
```

**Comment by gazayas** [comment]
Ok, thank you. I'll close this and take a closer look at everything

**Pull request closed without merging**
