### PR TITLE
[WIP] Add show community action

### PR DESCRIPTION
**Pull request by kytiken**
### Overview:概要
Add show community action

### Impact point:変更に関する影響箇所
- Add showCommunity action
- Add showCommunity to CommunityAPI
- Add get function to ApiRequest

### CODE REVIEW

**Comment by kytiken** [comment]
> Add get function to ApiRequest

404 error is expected.
What should I do at 404 error?

I think to create "Not found" component.
And "Not found" component render at 404 error.

How is that?

**Comment by chimame** [comment]
Is it 404 in API call? Not Found is a coding mistake or misconfiguration. 🤔 
If it is a get request, I think that it can be an error unconditionally except for normal(2xx etc).
For post and patch requests, I want to handle something other than 422 as an error.
It depends on backend API request design.

Although it is another topic, why is @murajun1978  in a commitment? 🔍

**Comment by kytiken** [comment]
I will create community show page to using redux-router.
Display to community show page with URL is `http://localhost:4000/communities/:id`.
I don't know what they will input `id`.

Is this method wrong?

> Although it is another topic, why is @murajun1978 in a commitment? 

Sorry. It might be miss rebase.

**Comment by chimame** [comment]
I see.
There seems to be a case where the community is displayed after it is deleted.
Let's render "Not found" component when 404 response. 👍 
In the end I would like to share processing.

**Comment by kytiken** [comment]
Thank you feedback to my comment. 😀 
I will commit to "Not found" component later.

**Comment by chimame** [comment]
sorry. merged https://github.com/shinosakarb/tebukuro/pull/129

**Pull request closed without merging**
