### PR TITLE
Add tickets_controller, adjust events_controller

### PR DESCRIPTION
**Pull request by gazayas**
### Overview:概要
This is a big pull request, so I put [WIP].
1. I added the tickets_controller
2. I made the routes shallow
3. Making the routes shallow affected the events, so I adjusted the events controller and tests.

### Technical changes:技術的変更点
Making the routes shallow

### Impact point:変更に関する影響箇所
Events are affected

### Change of UserInterface:UIの変更
None

Should the routes be shallow? I think it would be easier to manage the controllers. What do you think?
I know the user model should be made soon. I wonder how the routes will be affected.

Sorry for this pull request's size!

### CODE REVIEW

**Comment by gazayas** [comment]
Also, for some reason the `requests/tickets_spec.rb` test at line 41 is strange. Sometimes it passes, sometimes it doesn't.

**Comment by murajun1978** [comment]
FYI: https://www.relishapp.com/waterlink/rspec-json-expectations/docs/json-expectations/unordered-array-matching-support-for-include-json-matcher

**Comment by gazayas** [comment]
Cool, I think I'll use the include_unordered_json function

**Comment by gazayas** [comment]
I have a problem with the tests.

For the Ticket model association, this test passes (tickets_spec.rb)
```
it { is_expected.to have_one(:community).through(:event) }
```

But in community_spec.rb, this test does not pass
```
it { is_expected.to have_many(:tickets).through(:event) }
```

**Comment by murajun1978** [comment]
Ticket has many events.

try this  :blush:

```diff
# Community model
- has_many :tickets, through: :event
+ has_many :tickets, through: :events

# Community spec
- it { is_expected.to have_many(:tickets).through(:event) }
+ it { is_expected.to have_many(:tickets).through(:events) }
```

**Comment by gazayas** [comment]
It worked! Thank you.
I'll push the changes

**Comment by chimame** [comment]
👍

**Pull request merged**
