### PR TITLE
English translation of CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by gazayas**
### Overview:概要
An English translation of CONTRIBUTING.md

### Technical changes:技術的変更点
None

### Impact point:変更に関する影響箇所
None

### Change of UserInterface:UIの変更
No changes

### CODE REVIEW

**Comment by ytorii** [comment]
Thank you for English translation of CONTRIBUTING.md!
BTW, the wise saying that I quoted is a japanese translation of what [Jack Lemmon](https://en.wikipedia.org/wiki/Jack_Lemmon) said,

> Failure seldom stops you. What stops you is the fear of failure.

**Comment by gazayas** [comment]
Cool, thanks for letting me know! I'll write his name in too

**Comment by ytorii** [comment]
Thanks! And  could you please change the link to CONTRIBUTING.md in README_EN.md, to navigate your CONTRIBUTING_EN.md? Like below,
before: `For more details, visit [CONTRIBUTING.md](https://github.com/shinosakarb/tebukuro/blob/master/CONTRIBUTING.md).`

after:  `For more details, visit [CONTRIBUTING_EN.md](https://github.com/shinosakarb/tebukuro/blob/master/CONTRIBUTING_EN.md).`

**Comment by gazayas** [comment]
You got it

**Pull request merged**
