### PR TITLE
Add custom validator for datetime less

### PR DESCRIPTION
**Pull request by murajun1978**
### Overview:概要
We need a date and time diff custom matcher.

### Technical changes:技術的変更点
Add custom validator.

### Impact point:変更に関する影響箇所
nothing.

```
### options
validates :start_at, 
  datetime_less: { 
    less_than_or_equal_to: :end_at 
  }
validates :end_at, 
  datetime_less: { 
    greater_than_or_equal_to: :start_at 
  }
validates :start_at, 
  datetime_less: { 
    greater_than_or_equal_to: :created_at,
    greater_than_or_equal_to: :updated_at 
  }

### helper
validates_datetime_less_of :start_at, 
  less_than_or_equal_to: :created_at,
  greater_than_or_equal_to: updated_at
```

### CODE REVIEW

**Comment by chimame** [comment]
Do you need a test pattern of mandatory check of start date time?
I think it would be useful to add a helper method to `ActiveModel::Validations::HelperMethods`.

**Comment by murajun1978** [comment]
thank you for reviewing my pr.

yeah, I'll try refactoring ♻️

**Comment by chimame** [comment]
I thought about required check.
Are the "start date time" and "end date time" necessarily necessary for the size check of the date time?
For example, "end date time" is not required if you want to designate "from start date time". On the contrary, in the case of "until the end date time", "start date time" is not required.

By default, "start date time" and "end date time" can be mandatory checked, but I think that it is even better if it can be removed as an option(`from_blank: true`).

Is this overspecific?

**Comment by murajun1978** [comment]
Rails already has `allow_nil` option.

It's not DRY.

But, I know what you mean.

**Comment by chimame** [comment]
The example was bad. There was an "allow_nil" option.
There is no problem with the start date time, but what about the end date time?
Shall we think about it now?

**Comment by murajun1978** [comment]
Yeah, i think that need it.

they seem to be a bug.

```
e.g.

# your idea
validates :start_at, 
  datetime_less: {
    before: :end_at, 
    from_blank: true
  }

validates :end_at, 
  presence: true

# my idea
validates :start_at, 
  datetime_less: {
    before: :end_at #required
  }

validates :end_at, 
  allow_nil: true
```

do i think too much?

well, I thought that option is necessary 😇

**Comment by chimame** [comment]
Sorry for being confused by my comment, I was wrongly misrecognized.
In Rails you can also check such numbers.

```rb
validates :from_year, numericality: { only_integer: true, greater_than: 1900, less_than: :to_year}
validates :to_year, numericality: { only_integer: true, greater_than: :from_year, less_than: 2017}
```

So let's do the same as "numericality".

```rb
validates :start_at, datetime_less: {less_than: :end_at}
#example => validates :end_at, datetime_less: {greater_than: :start_at}
```
Using the `if` option if validation processing is not done if `end_at` is blank.
How about with specifications that `less_than` and `greater_than` check as if values exist?
So your current code as it is. If you dare say, `before` is not intuitive.

**Comment by murajun1978** [comment]
Add `:after` to options and check options.

```
### ArgumentError
validates :start_at, datetime_less: {}
validates :start_at, datetime_less: {before: :end_at, after: :end_at}

### Running validation
validates :start_at, datetime_less: {before: :end_at}
validates :end_at,  datetime_less: {after: :start_at}
```

**Comment by murajun1978** [comment]
Change option keys.

**Comment by murajun1978** [comment]
@chimame please, review again 🙇

**Comment by chimame** [comment]
Thank you for refactoring. I think that overall is good. 👍 
But there are places to worry about.
* You added to `config/locales/defaults`, but would you like to add `config/locales/custom`? Because this is the place to store Rails default settings, we want to respond by just replacing the files when upgrading.
* I think that the Japanese of `より以前` or `より以後` is strange. I think that it is `より前` or `より後`.

I knew for the first time that [slice](https://github.com/rails/rails/blob/92703a9ea5d8b96f30e0b706b801c9185ef14f0e/activesupport/lib/active_support/core_ext/hash/slice.rb#L21) was extended with ActiveSupport in the Hash class. 😀

**Comment by murajun1978** [comment]
I think that `config/locales/defaults` is locale data for Application, not Rails.

Should i split the file ?

**Comment by chimame** [comment]
It's exactly as you say. I was misunderstanding. `config/locals/defaults` is Application.
Please split it under `config/locals/defaults`. (ex. `config/locals/defaults/datetime_less.en.yml`)

**Comment by murajun1978** [comment]
Split locale data.

**Comment by chimame** [comment]
LGTM 👍

**Pull request merged**
