### PR TITLE
Update packages

### PR DESCRIPTION
**Pull request by ogom**
### Overview

#49 
Update dependencies and devDependencies packages of package.json.

### Technical changes

* packages
  * webpack 2(bata)
  * react-redux 5(rc)

### Testing

Access URL of `http://localhost:4000/` .

```
$ cd front/
$ npm start
```

### CODE REVIEW

**Comment by chimame** [comment]
webpack.config.jsは`root/client/config/webpack/`にありますよ？今のままなら何かまずいですか？

**Comment by chimame** [comment]
Webpack.config.js already exists in `clicnet/config/webpack`.

**Comment by ogom** [comment]
Fix to load `config/webpack/webpack.dev.config.js` file.

**Comment by chimame** [comment]
Would you like to upgrade React, React-dom and all others?

**Comment by ogom** [comment]
Yes, this is all updates.

**Comment by chimame** [comment]
OK. If that is the case please update the following package.
* react(react-dom) 15.4.1
* react-redux 4.4.6

**Comment by ogom** [comment]
Update npm package.

* react: 15.4.1
* react-dom: 15.4.1
* react-redux: 5.0.0-rc.1

**Comment by chimame** [comment]
LGTM

**Pull request merged**
